-- Supabase Setup Script for Dar Care

-- 1. Create a public 'users' table to store user profiles
-- This table mirrors auth.users and is safe to join in queries
create table public.users (
  id uuid references auth.users not null primary key,
  full_name text,
  avatar_url text,
  role text check (role in ('client', 'provider', 'admin')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) on users
alter table public.users enable row level security;

-- Policy: Allow users to view their own profile
create policy "Users can view own profile" on public.users
  for select using (auth.uid() = id);

-- Policy: Allow users to update their own profile
create policy "Users can update own profile" on public.users
  for update using (auth.uid() = id);

-- Policy: Allow public read access to basic user info (needed for provider profiles)
create policy "Public profiles are viewable by everyone" on public.users
  for select using (true);


-- 2. Create 'departments' table (Service Categories)
create table public.departments (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  image_url text, -- For category icon
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on departments
alter table public.departments enable row level security;

-- Policy: Allow public read access to departments
create policy "Departments are viewable by everyone" on public.departments
  for select using (true);


-- 3. Create 'providers' table
create table public.providers (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) not null,
  department_id bigint references public.departments(id), -- Links provider to a department
  avg_rating numeric default 0,
  hourly_rate numeric,
  experience_years int default 0,
  status text default 'pending', -- pending, approved, suspended
  bio text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on providers
alter table public.providers enable row level security;

-- Policy: Allow public read access to providers
create policy "Providers are viewable by everyone" on public.providers
  for select using (true);

-- Policy: Allow providers to update their own record
create policy "Providers can update own info" on public.providers
  for update using (auth.uid() = user_id);

-- Policy: Allow providers to insert their own record
create policy "Providers can insert own info" on public.providers
  for insert with check (auth.uid() = user_id);

-- 3.1 Create 'clients' table
create table public.clients (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on clients
alter table public.clients enable row level security;

-- Policy: Clients can read own data
create policy "Clients can view own data" on public.clients
  for select using (auth.uid() = user_id);

-- Policy: Clients can insert own data
create policy "Clients can insert own data" on public.clients
  for insert with check (auth.uid() = user_id);


-- 4. Function to automatically create a user profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, full_name, avatar_url, role)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'role');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on auth.users insert
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 5. Seed Data (Optional - useful for testing)
-- Insert some departments
insert into public.departments (name, description) values
('Plumbing', 'Fixing leaks and pipes'),
('Electrical', 'Wiring and electrical repairs'),
('Cleaning', 'Home and office cleaning'),
('Painting', 'Interior and wall painting'),
('Carpentry', 'Woodwork and furniture repair');

-- Note: You will need to sign up users via the app to populate the 'users' table,
-- then you can manually insert into 'providers' linking those users to departments.

