-- 6. Create 'orders' table
create table public.orders (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) not null,
  provider_id bigint references public.providers(id) not null,
  service_date timestamp with time zone not null,
  status text check (status in ('pending', 'confirmed', 'completed', 'cancelled')) default 'pending',
  total_amount numeric,
  address text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on orders
alter table public.orders enable row level security;

-- Policy: Clients can view their own orders
create policy "Clients can view own orders" on public.orders
  for select using (auth.uid() = (select user_id from public.clients where id = client_id));

-- Policy: Providers can view orders assigned to them
create policy "Providers can view assigned orders" on public.orders
  for select using (auth.uid() = (select user_id from public.providers where id = provider_id));

-- Policy: Clients can create orders
create policy "Clients can create orders" on public.orders
  for insert with check (auth.uid() = (select user_id from public.clients where id = client_id));

-- 7. Create 'favorites' table
create table public.favorites (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) not null,
  provider_id bigint references public.providers(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(client_id, provider_id)
);

-- Enable RLS on favorites
alter table public.favorites enable row level security;

-- Policy: Clients can view own favorites
create policy "Clients can view own favorites" on public.favorites
  for select using (auth.uid() = (select user_id from public.clients where id = client_id));

-- Policy: Clients can add to favorites
create policy "Clients can add favorites" on public.favorites
  for insert with check (auth.uid() = (select user_id from public.clients where id = client_id));

-- Policy: Clients can remove from favorites
create policy "Clients can remove favorites" on public.favorites
  for delete using (auth.uid() = (select user_id from public.clients where id = client_id));

