interface CountryType {
  code: string;
  label: string;
  id: string;
  flag: string;
}

export const dialCodes: CountryType[] = [
  {
    label: "Saudi Arabia",
    id: "+966",
    code: "SA",
    flag: "🇸🇦",
  },
  { label: "Turkey", id: "+90", code: "TR", flag: "🇹🇷" },
  { label: "Egypt", id: "+20", code: "EG", flag: "🇪🇬" },
  {
    label: "United Arab Emirates",
    id: "+971",
    code: "AE",
    flag: "🇦🇪",
  },
  { label: "Afghanistan", id: "+93", code: "AF", flag: "🇦🇫" },
  { label: "Albania", id: "+355", code: "AL", flag: "🇦🇱" },
  { label: "Algeria", id: "+213", code: "DZ", flag: "🇩🇿" },
  { label: "AmericanSamoa", id: "+1684", code: "AS", flag: "🇦🇸" },
  { label: "Andorra", id: "+376", code: "AD", flag: "🇦🇩" },
  { label: "Angola", id: "+244", code: "AO", flag: "🇦🇴" },
  { label: "Anguilla", id: "+1264", code: "AI", flag: "🇦🇮" },
  { label: "Antarctica", id: "+672", code: "AQ", flag: "🇦🇶" },
  { label: "Antigua and Barbuda", id: "+1268", code: "AG", flag: "🇦🇬" },
  { label: "Argentina", id: "+54", code: "AR", flag: "🇦🇷" },
  { label: "Armenia", id: "+374", code: "AM", flag: "🇦🇲" },
  { label: "Aruba", id: "+297", code: "AW", flag: "🇦🇼" },
  {
    label: "Australia",
    id: "+61",
    code: "AU",
    flag: "🇦🇺",
  },
  { label: "Austria", id: "+43", code: "AT", flag: "🇦🇹" },
  { label: "Azerbaijan", id: "+994", code: "AZ", flag: "🇦🇿" },
  { label: "Bahamas", id: "+1242", code: "BS", flag: "🇧🇸" },
  {
    label: "Bahrain",
    id: "+973",
    code: "BH",
    flag: "🇧🇭",
  },
  { label: "Bangladesh", id: "+880", code: "BD", flag: "🇧🇩" },
  { label: "Barbados", id: "+1246", code: "BB", flag: "🇧🇧" },
  { label: "Belarus", id: "+375", code: "BY", flag: "🇧🇾" },
  { label: "Belgium", id: "+32", code: "BE", flag: "🇧🇪" },
  { label: "Belize", id: "+501", code: "BZ", flag: "🇧🇿" },
  { label: "Benin", id: "+229", code: "BJ", flag: "🇧🇯" },
  { label: "Bermuda", id: "+1441", code: "BM", flag: "🇧🇲" },
  { label: "Bhutan", id: "+975", code: "BT", flag: "🇧🇹" },
  {
    label: "Bolivia, Plurinational State of",
    id: "+591",
    code: "BO",
    flag: "🇧🇴",
  },
  { label: "Bosnia and Herzegovina", id: "+387", code: "BA", flag: "🇧🇦" },
  { label: "Botswana", id: "+267", code: "BW", flag: "🇧🇼" },
  { label: "Brazil", id: "+55", code: "BR", flag: "🇧🇷" },
  {
    label: "British Indian Ocean Territory",
    id: "+246",
    code: "IO",
    flag: "🇮🇴",
  },
  { label: "Brunei Darussalam", id: "+673", code: "BN", flag: "🇧🇳" },
  { label: "Bulgaria", id: "+359", code: "BG", flag: "🇧🇬" },
  { label: "Burkina Faso", id: "+226", code: "BF", flag: "🇧🇫" },
  { label: "Burundi", id: "+257", code: "BI", flag: "🇧🇮" },
  { label: "Cambodia", id: "+855", code: "KH", flag: "🇰🇭" },
  { label: "Cameroon", id: "+237", code: "CM", flag: "🇨🇲" },
  { label: "Canada", id: "+1", code: "CA", flag: "🇨🇦" },
  { label: "Cape Verde", id: "+238", code: "CV", flag: "🇨🇻" },
  { label: "Cayman Islands", id: "+345", code: "KY", flag: "🇰🇾" },
  {
    label: "Central African Republic",
    id: "+236",
    code: "CF",
    flag: "🇨🇫",
  },
  { label: "Chad", id: "+235", code: "TD", flag: "🇹🇩" },
  { label: "Chile", id: "+56", code: "CL", flag: "🇨🇱" },
  { label: "China", id: "+86", code: "CN", flag: "🇨🇳" },
  { label: "Christmas Island", id: "+61", code: "CX", flag: "🇨🇽" },
  { label: "Cocos (Keeling) Islands", id: "+61", code: "CC", flag: "🇨🇨" },
  { label: "Colombia", id: "+57", code: "CO", flag: "🇨🇴" },
  { label: "Comoros", id: "+269", code: "KM", flag: "🇰🇲" },
  { label: "Congo", id: "+242", code: "CG", flag: "🇨🇬" },
  {
    label: "Congo, The Democratic Republic of the",
    id: "+243",
    code: "CD",
    flag: "🇨🇩",
  },
  { label: "Cook Islands", id: "+682", code: "CK", flag: "🇨🇰" },
  { label: "Costa Rica", id: "+506", code: "CR", flag: "🇨🇷" },
  { label: "Cote d'Ivoire", id: "+225", code: "CI", flag: "🇨🇮" },
  { label: "Croatia", id: "+385", code: "HR", flag: "🇭🇷" },
  { label: "Cuba", id: "+53", code: "CU", flag: "🇨🇺" },
  { label: "Cyprus", id: "+357", code: "CY", flag: "🇨🇾" },
  { label: "Czech Republic", id: "+420", code: "CZ", flag: "🇨🇿" },
  { label: "Curaçao", id: "+599", code: "CW", flag: "🇨🇼" },
  { label: "Canary Islands", id: "+34", code: "IC", flag: "🇮🇨" },
  { label: "Denmark", id: "+45", code: "DK", flag: "🇩🇰" },
  { label: "Djibouti", id: "+253", code: "DJ", flag: "🇩🇯" },
  { label: "Dominica", id: "+1767", code: "DM", flag: "🇩🇲" },
  {
    label: "Dominican Republic",
    id: "+1849",
    code: "DO",
    flag: "🇩🇴",
  },
  {
    label: "Dominican Republic",
    id: "+1829",
    code: "DO",
    flag: "🇩🇴",
  },
  {
    label: "Dominican Republic",
    id: "+1809",
    code: "DO",
    flag: "🇩🇴",
  },
  { label: "Ecuador", id: "+593", code: "EC", flag: "🇪🇨" },

  { label: "El Salvador", id: "+503", code: "SV", flag: "🇸🇻" },
  { label: "Equatorial Guinea", id: "+240", code: "GQ", flag: "🇬🇶" },
  { label: "Eritrea", id: "+291", code: "ER", flag: "🇪🇷" },
  { label: "Estonia", id: "+372", code: "EE", flag: "🇪🇪" },
  { label: "Ethiopia", id: "+251", code: "ET", flag: "🇪🇹" },
  {
    label: "Falkland Islands (Malvinas)",
    id: "+500",
    code: "FK",
    flag: "🇫🇰",
  },
  { label: "Faroe Islands", id: "+298", code: "FO", flag: "🇫🇴" },
  { label: "Fiji", id: "+679", code: "FJ", flag: "🇫🇯" },
  { label: "Finland", id: "+358", code: "FI", flag: "🇫🇮" },
  { label: "France", id: "+33", code: "FR", flag: "🇫🇷" },
  { label: "French Guiana", id: "+594", code: "GF", flag: "🇬🇫" },
  { label: "French Polynesia", id: "+689", code: "PF", flag: "🇵🇫" },
  {
    label: "French Southern Territories",
    id: "+262",
    code: "TF",
    flag: "🇹🇫",
  },
  { label: "Gabon", id: "+241", code: "GA", flag: "🇬🇦" },
  { label: "Gambia", id: "+220", code: "GM", flag: "🇬🇲" },
  { label: "Georgia", id: "+995", code: "GE", flag: "🇬🇪" },
  { label: "Germany", id: "+49", code: "DE", flag: "🇩🇪" },
  { label: "Ghana", id: "+233", code: "GH", flag: "🇬🇭" },
  { label: "Gibraltar", id: "+350", code: "GI", flag: "🇬🇮" },
  { label: "Greece", id: "+30", code: "GR", flag: "🇬🇷" },
  { label: "Greenland", id: "+299", code: "GL", flag: "🇬🇱" },
  { label: "Grenada", id: "+1473", code: "GD", flag: "🇬🇩" },
  { label: "Guadeloupe", id: "+590", code: "GP", flag: "🇬🇵" },
  { label: "Guam", id: "+1671", code: "GU", flag: "🇬🇺" },
  { label: "Guatemala", id: "+502", code: "GT", flag: "🇬🇹" },
  { label: "Guernsey", id: "+44", code: "GG", flag: "🇬🇬" },
  { label: "Guinea", id: "+224", code: "GN", flag: "🇬🇳" },
  { label: "Guinea-Bissau", id: "+245", code: "GW", flag: "🇬🇼" },
  { label: "Guyana", id: "+592", code: "GY", flag: "🇬🇾" },
  { label: "Haiti", id: "+509", code: "HT", flag: "🇭🇹" },
  {
    label: "Heard & McDonald Islands",
    id: "+672",
    code: "HM",
    flag: "🇭🇲",
  },
  {
    label: "Holy See (Vatican City State)",
    id: "+379",
    code: "VA",
    flag: "🇻🇦",
  },
  { label: "Honduras", id: "+504", code: "HN", flag: "🇭🇳" },
  { label: "Hong Kong", id: "+852", code: "HK", flag: "🇭🇰" },
  { label: "Hungary", id: "+36", code: "HU", flag: "🇭🇺" },
  { label: "Iceland", id: "+354", code: "IS", flag: "🇮🇸" },
  { label: "India", id: "+91", code: "IN", flag: "🇮🇳" },
  { label: "Indonesia", id: "+62", code: "ID", flag: "🇮🇩" },
  {
    label: "Iran, Islamic Republic of",
    id: "+98",
    code: "IR",
    flag: "🇮🇷",
  },
  { label: "Iraq", id: "+964", code: "IQ", flag: "🇮🇶" },
  { label: "Ireland", id: "+353", code: "IE", flag: "🇮🇪" },
  { label: "Isle of Man", id: "+44", code: "IM", flag: "🇮🇲" },
  { label: "Italy", id: "+39", code: "IT", flag: "🇮🇹" },
  {
    label: "Jamaica",
    id: "+1876",
    code: "JM",
    flag: "🇯🇲",
  },
  {
    label: "Jamaica",
    id: "+1658",
    code: "JM",
    flag: "🇯🇲",
  },
  { label: "Japan", id: "+81", code: "JP", flag: "🇯🇵" },
  { label: "Jersey", id: "+44", code: "JE", flag: "🇯🇪" },
  {
    label: "Jordan",
    id: "+962",
    code: "JO",
    flag: "🇯🇴",
  },
  { label: "Kazakhstan", id: "+77", code: "KZ", flag: "🇰🇿" },
  { label: "Kenya", id: "+254", code: "KE", flag: "🇰🇪" },
  { label: "Kiribati", id: "+686", code: "KI", flag: "🇰🇮" },
  {
    label: "Korea, Democratic People's Republic of",
    id: "+850",
    code: "KP",
    flag: "🇰🇵",
  },
  { label: "Korea, Republic of", id: "+82", code: "KR", flag: "🇰🇷" },
  {
    label: "Kuwait",
    id: "+965",
    code: "KW",
    flag: "🇰🇼",
  },
  { label: "Kyrgyzstan", id: "+996", code: "KG", flag: "🇰🇬" },
  { label: "Kosovo", id: "+383", code: "XK", flag: "🇽🇰" },
  {
    label: "Lao People's Democratic Republic",
    id: "+856",
    code: "LA",
    flag: "🇱🇦",
  },
  { label: "Latvia", id: "+371", code: "LV", flag: "🇱🇻" },
  { label: "Lebanon", id: "+961", code: "LB", flag: "🇱🇧" },
  { label: "Lesotho", id: "+266", code: "LS", flag: "🇱🇸" },
  { label: "Liberia", id: "+231", code: "LR", flag: "🇱🇷" },
  { label: "Libyan Arab Jamahiriya", id: "+218", code: "LY", flag: "🇱🇾" },
  { label: "Liechtenstein", id: "+423", code: "LI", flag: "🇱🇮" },
  { label: "Lithuania", id: "+370", code: "LT", flag: "🇱🇹" },
  { label: "Luxembourg", id: "+352", code: "LU", flag: "🇱🇺" },
  { label: "Macao", id: "+853", code: "MO", flag: "🇲🇴" },
  {
    label: "Macedonia, The Former Yugoslav Republic of",
    id: "+389",
    code: "MK",
    flag: "🇲🇰",
  },
  { label: "Madagascar", id: "+261", code: "MG", flag: "🇲🇬" },
  { label: "Malawi", id: "+265", code: "MW", flag: "🇲🇼" },
  { label: "Malaysia", id: "+60", code: "MY", flag: "🇲🇾" },
  { label: "Maldives", id: "+960", code: "MV", flag: "🇲🇻" },
  { label: "Mali", id: "+223", code: "ML", flag: "🇲🇱" },
  { label: "Malta", id: "+356", code: "MT", flag: "🇲🇹" },
  { label: "Marshall Islands", id: "+692", code: "MH", flag: "🇲🇭" },
  { label: "Martinique", id: "+596", code: "MQ", flag: "🇲🇶" },
  { label: "Mauritania", id: "+222", code: "MR", flag: "🇲🇷" },
  { label: "Mauritius", id: "+230", code: "MU", flag: "🇲🇺" },
  { label: "Mayotte", id: "+262", code: "YT", flag: "🇾🇹" },
  { label: "Mexico", id: "+52", code: "MX", flag: "🇲🇽" },
  {
    label: "Micronesia, Federated States of",
    id: "+691",
    code: "FM",
    flag: "🇫🇲",
  },
  { label: "Moldova, Republic of", id: "+373", code: "MD", flag: "🇲🇩" },
  { label: "Monaco", id: "+377", code: "MC", flag: "🇲🇨" },
  { label: "Mongolia", id: "+976", code: "MN", flag: "🇲🇳" },
  { label: "Montenegro", id: "+382", code: "ME", flag: "🇲🇪" },
  { label: "Montserrat", id: "+1664", code: "MS", flag: "🇲🇸" },
  { label: "Morocco", id: "+212", code: "MA", flag: "🇲🇦" },
  { label: "Mozambique", id: "+258", code: "MZ", flag: "🇲🇿" },
  { label: "Myanmar", id: "+95", code: "MM", flag: "🇲🇲" },
  { label: "Namibia", id: "+264", code: "NA", flag: "🇳🇦" },
  { label: "Nauru", id: "+674", code: "NR", flag: "🇳🇷" },
  { label: "Nepal", id: "+977", code: "NP", flag: "🇳🇵" },
  { label: "Netherlands", id: "+31", code: "NL", flag: "🇳🇱" },
  { label: "Caribbean Netherlands", id: "+599", code: "BQ", flag: "🇧🇶" },
  { label: "New Caledonia", id: "+687", code: "NC", flag: "🇳🇨" },
  { label: "New Zealand", id: "+64", code: "NZ", flag: "🇳🇿" },
  { label: "Nicaragua", id: "+505", code: "NI", flag: "🇳🇮" },
  { label: "Niger", id: "+227", code: "NE", flag: "🇳🇪" },
  { label: "Nigeria", id: "+234", code: "NG", flag: "🇳🇬" },
  { label: "Niue", id: "+683", code: "NU", flag: "🇳🇺" },
  { label: "Norfolk Island", id: "+672", code: "NF", flag: "🇳🇫" },
  {
    label: "Northern Mariana Islands",
    id: "+1670",
    code: "MP",
    flag: "🇲🇵",
  },
  { label: "Norway", id: "+47", code: "NO", flag: "🇳🇴" },
  { label: "Oman", id: "+968", code: "OM", flag: "🇴🇲" },
  { label: "Pakistan", id: "+92", code: "PK", flag: "🇵🇰" },
  { label: "Palau", id: "+680", code: "PW", flag: "🇵🇼" },
  {
    label: "Palestinian Territory, Occupied",
    id: "+970",
    code: "PS",
    flag: "🇵🇸",
  },
  { label: "Panama", id: "+507", code: "PA", flag: "🇵🇦" },
  { label: "Papua New Guinea", id: "+675", code: "PG", flag: "🇵🇬" },
  { label: "Paraguay", id: "+595", code: "PY", flag: "🇵🇾" },
  { label: "Peru", id: "+51", code: "PE", flag: "🇵🇪" },
  { label: "Philippines", id: "+63", code: "PH", flag: "🇵🇭" },
  { label: "Pitcairn", id: "+872", code: "PN", flag: "🇵🇳" },
  { label: "Poland", id: "+48", code: "PL", flag: "🇵🇱" },
  { label: "Portugal", id: "+351", code: "PT", flag: "🇵🇹" },
  {
    label: "Puerto Rico",
    id: "+1939",
    code: "PR",
    flag: "🇵🇷",
  },
  {
    label: "Puerto Rico",
    id: "+1787",
    code: "PR",
    flag: "🇵🇷",
  },
  { label: "Qatar", id: "+974", code: "QA", flag: "🇶🇦" },
  { label: "Romania", id: "+40", code: "RO", flag: "🇷🇴" },
  { label: "Russia", id: "+7", code: "RU", flag: "🇷🇺" },
  { label: "Rwanda", id: "+250", code: "RW", flag: "🇷🇼" },
  { label: "Réunion", id: "+262", code: "RE", flag: "🇷🇪" },
  { label: "Saint Barthélemy", id: "+590", code: "BL", flag: "🇧🇱" },
  {
    label: "Saint Helena, Ascension and Tristan Da Cunha",
    id: "+290",
    code: "SH",
    flag: "🇸🇭",
  },
  { label: "Saint Kitts and Nevis", id: "+1869", code: "KN", flag: "🇰🇳" },
  { label: "Saint Lucia", id: "+1758", code: "LC", flag: "🇱🇨" },
  { label: "Saint Martin", id: "+590", code: "MF", flag: "🇲🇫" },
  {
    label: "Saint Pierre and Miquelon",
    id: "+508",
    code: "PM",
    flag: "🇵🇲",
  },
  {
    label: "Saint Vincent and the Grenadines",
    id: "+1784",
    code: "VC",
    flag: "🇻🇨",
  },
  { label: "Samoa", id: "+685", code: "WS", flag: "🇼🇸" },
  { label: "San Marino", id: "+378", code: "SM", flag: "🇸🇲" },
  { label: "Sao Tome and Principe", id: "+239", code: "ST", flag: "🇸🇹" },
  { label: "Senegal", id: "+221", code: "SN", flag: "🇸🇳" },
  { label: "Serbia", id: "+381", code: "RS", flag: "🇷🇸" },
  { label: "Seychelles", id: "+248", code: "SC", flag: "🇸🇨" },
  { label: "Sierra Leone", id: "+232", code: "SL", flag: "🇸🇱" },
  { label: "Singapore", id: "+65", code: "SG", flag: "🇸🇬" },
  { label: "Slovakia", id: "+421", code: "SK", flag: "🇸🇰" },
  { label: "Slovenia", id: "+386", code: "SI", flag: "🇸🇮" },
  { label: "Solomon Islands", id: "+677", code: "SB", flag: "🇸🇧" },
  { label: "Somalia", id: "+252", code: "SO", flag: "🇸🇴" },
  { label: "South Africa", id: "+27", code: "ZA", flag: "🇿🇦" },
  {
    label: "South Georgia and the South Sandwich Islands",
    id: "+500",
    code: "GS",
    flag: "🇬🇸",
  },
  { label: "Spain", id: "+34", code: "ES", flag: "🇪🇸" },
  { label: "Sri Lanka", id: "+94", code: "LK", flag: "🇱🇰" },
  { label: "Sudan", id: "+249", code: "SD", flag: "🇸🇩" },
  { label: "South Sudan", id: "+211", code: "SS", flag: "🇸🇸" },
  { label: "Surilabel", id: "+597", code: "SR", flag: "🇸🇷" },
  { label: "Svalbard and Jan Mayen", id: "+47", code: "SJ", flag: "🇸🇯" },
  { label: "Swaziland", id: "+268", code: "SZ", flag: "🇸🇿" },
  { label: "Sweden", id: "+46", code: "SE", flag: "🇸🇪" },
  { label: "Switzerland", id: "+41", code: "CH", flag: "🇨🇭" },
  { label: "Syrian Arab Republic", id: "+963", code: "SY", flag: "🇸🇾" },
  { label: "Sint Maarten", id: "+721", code: "SX", flag: "🇸🇽" },
  {
    label: "Taiwan, Province of China",
    id: "+886",
    code: "TW",
    flag: "🇹🇼",
  },
  { label: "Tajikistan", id: "+992", code: "TJ", flag: "🇹🇯" },
  {
    label: "Tanzania, United Republic of",
    id: "+255",
    code: "TZ",
    flag: "🇹🇿",
  },
  { label: "Thailand", id: "+66", code: "TH", flag: "🇹🇭" },
  { label: "Timor-Leste", id: "+670", code: "TL", flag: "🇹🇱" },
  { label: "Togo", id: "+228", code: "TG", flag: "🇹🇬" },
  { label: "Tokelau", id: "+690", code: "TK", flag: "🇹🇰" },
  { label: "Tonga", id: "+676", code: "TO", flag: "🇹🇴" },
  { label: "Trinidad and Tobago", id: "+1868", code: "TT", flag: "🇹🇹" },
  { label: "Tunisia", id: "+216", code: "TN", flag: "🇹🇳" },
  { label: "Turkmenistan", id: "+993", code: "TM", flag: "🇹🇲" },
  {
    label: "Turks and Caicos Islands",
    id: "+1649",
    code: "TC",
    flag: "🇹🇨",
  },
  { label: "Tuvalu", id: "+688", code: "TV", flag: "🇹🇻" },
  { label: "Uganda", id: "+256", code: "UG", flag: "🇺🇬" },
  { label: "Ukraine", id: "+380", code: "UA", flag: "🇺🇦" },

  {
    label: "United Kingdom",
    id: "+44",
    code: "GB",
    flag: "🇬🇧",
  },
  {
    label: "United States",
    id: "+1",
    code: "US",
    flag: "🇺🇸",
  },
  { label: "Uruguay", id: "+598", code: "UY", flag: "🇺🇾" },
  { label: "Uzbekistan", id: "+998", code: "UZ", flag: "🇺🇿" },
  { label: "Vanuatu", id: "+678", code: "VU", flag: "🇻🇺" },
  {
    label: "Venezuela, Bolivarian Republic of",
    id: "+58",
    code: "VE",
    flag: "🇻🇪",
  },
  { label: "Viet Nam", id: "+84", code: "VN", flag: "🇻🇳" },
  {
    label: "Virgin Islands, British",
    id: "+1284",
    code: "VG",
    flag: "🇻🇬",
  },
  { label: "Virgin Islands, U.S.", id: "+1340", code: "VI", flag: "🇻🇮" },
  { label: "Wallis and Futuna", id: "+681", code: "WF", flag: "🇼🇫" },
  { label: "Western Sarah", id: "+212", code: "EH", flag: "🇪🇭" },
  { label: "Yemen", id: "+967", code: "YE", flag: "🇾🇪" },
  { label: "Zambia", id: "+260", code: "ZM", flag: "🇿🇲" },
  { label: "Zimbabwe", id: "+263", code: "ZW", flag: "🇿🇼" },
  { label: "Åland Islands", id: "+358", code: "AX", flag: "🇦🇽" },
];
