// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9cnDxnTnzAwZeHyDa4GO2jqQv005zg0A',
    appId: '1:491373625352:web:01c13649e75fa3ef1811bd',
    messagingSenderId: '491373625352',
    projectId: 'darcare-b0d24',
    authDomain: 'darcare-b0d24.firebaseapp.com',
    storageBucket: 'darcare-b0d24.firebasestorage.app',
    measurementId: 'G-8BEWE88SY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYommANrbxV_oLy_i8cOPCR75i4_tuonE',
    appId: '1:491373625352:android:f660b119d3ee4da61811bd',
    messagingSenderId: '491373625352',
    projectId: 'darcare-b0d24',
    storageBucket: 'darcare-b0d24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBONxocfjFAMqgVa6YWrWv7WU3agZHMjXc',
    appId: '1:491373625352:ios:a341900ecc086b581811bd',
    messagingSenderId: '491373625352',
    projectId: 'darcare-b0d24',
    storageBucket: 'darcare-b0d24.firebasestorage.app',
    iosBundleId: 'com.example.darCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBONxocfjFAMqgVa6YWrWv7WU3agZHMjXc',
    appId: '1:491373625352:ios:a341900ecc086b581811bd',
    messagingSenderId: '491373625352',
    projectId: 'darcare-b0d24',
    storageBucket: 'darcare-b0d24.firebasestorage.app',
    iosBundleId: 'com.example.darCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9cnDxnTnzAwZeHyDa4GO2jqQv005zg0A',
    appId: '1:491373625352:web:1a0bb1fd8f597bf21811bd',
    messagingSenderId: '491373625352',
    projectId: 'darcare-b0d24',
    authDomain: 'darcare-b0d24.firebaseapp.com',
    storageBucket: 'darcare-b0d24.firebasestorage.app',
    measurementId: 'G-9G3LLCXPXR',
  );
}
